# Generated by Django 5.2.5 on 2025-08-28 21:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="postcategory",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
