# Generated by Django 5.2.5 on 2025-08-28 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_created_at_postcategory_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="postcategory",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
